# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty

os:
  - linux
  - osx
  
osx_image: xcode9
r:
  - release
  - devel
matrix:
  allow_failures:
  - r: devel

after_success:
    - Rscript -e 'covr::coveralls()'
    - Rscript -e 'install.packages("remotes")' -e 'remotes::install_github("hadley/pkgdown")' -e 'pkgdown::build_site()'
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master